services:
  prefect-server:
    container_name: prefect-server
    build:
      context: .
      dockerfile: Dockerfile
    env_file: .env
    volumes:
      - /data/plaid/prefect:/home/prefect
    ports:
      - 4200:4200
    restart: unless-stopped
  
  prefect-worker-1:
    container_name: prefect-worker-1
    build:
      context: .
      dockerfile: Dockerfile
    command: prefect worker start --pool default-work-pool
    env_file: .env
    restart: unless-stopped
  
  metabase-db:
    container_name: metabase-db
    image: postgres:13.1-alpine
    restart: unless-stopped
    volumes:
      - /data/metabase/db:/var/lib/postgresql/data
    env_file: .env

  metabase:
    image: metabase/metabase:latest
    container_name: metabase
    restart: unless-stopped
    env_file: .env
    ports:
      - 3333:3000
    depends_on:
      - metabase-db
