version: 2

sources:
  - name: plaid
    database: plaid
    schema: raw
    tables:
      - name: accounts
      - name: transactions_json
      - name: institutions
      - name: merchant_filter
  - name: plaid-util
    database: plaid
    schema: util
    tables:
      - name: calendar
